parameters:
  - name: pretty_print
    in: query
    description: Pretty print response
    schema:
      type: boolean
get:
  tags:
    - products
  summary: Get products by products name
  description: |
    Some description of the operation.
    You can use `Markdown` here.
  operationId: getProdutcsByName
  parameters:
    - name: products
      in: path
      description: The name that needs to be fetched
      required: true
      schema:
        type: string
    - name: with_email
      in: query
      description: Filter users without email
      schema:
        type: boolean

  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../components/schemas/products.yaml
          example:
            username: user1
            email: products@example.com
    '403':
      description: Forbidden
      $ref: ../components/responses/Problem.yaml
    '404':
      description: products not found
      $ref: ../components/responses/Problem.yaml
put:
  tags:
    - products
  summary: Updated products
  description: This can only be done by the logged in products.
  operationId: updateUser
  parameters:
    - name: products
      in: path
      description: The name that needs to be updated
      required: true
      schema:
        type: string
  security:
    - main_auth:
        - write:users
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/products.yaml
      application/xml:
        schema:
          $ref: ../components/schemas/products.yaml
    description: Updated products object
    required: true
  responses:
    '200':
      description: OK
    '400':
      description: Invalid products supplied
      $ref: ../components/responses/Problem.yaml
    '404':
      description: products not found
      $ref: ../components/responses/Problem.yaml
